development:
  adapter: postgresql
  encoding: utf8
  database: devsmix_development
  username: <%= `whoami`.strip %>
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: devsmix_test
  username: <%= `whoami`.strip %>
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: devsmix_production
  username: <%= `whoami`.strip %>
  pool: 5
  timeout: 5000
